name: Ghcr.io Cleanup Action

description: >
  Delete untagged/tagged images from the GitHub Container Registry. Supports
  multi architecture and attestation images.

author: Dataaxiom Inc

branding:
  icon: trash-2
  color: blue

inputs:
  owner:
    description: >
      Owner of the package (user or organization)
    required: false

  repository:
    description: >
      The GitHub repository where the package is stored. Defaults to repository
      name.
    required: false

  package:
    description: >
      The package name. Defaults to the repository name.
    required: false

  token:
    description: >
      Token to authenticate with the ghcr.io registry and the GitHub API
    required: true

  tags:
    description: >
      Tags to delete (comma seperated) - Short form of delete-tags input option
    required: false

  delete-tags:
    description: >
      Tags to delete (comma seperated)
    required: false

  delete-untagged:
    description: >
      Delete untagged images (true/false). Default option which is set to true
      when no other options set
    required: false

  delete-ghost-images:
    description: >
      Include for deletion multi architecture images where all underlying
      platform images are missing (true/false).
    required: false

  delete-partial-images:
    description: >
      Include for deletion multi architecture images with partial underlying
      platform images are missing (true/false).
    required: false

  keep-n-untagged:
    description: >
      Number of untagged images to keep (sorted by date)
    required: false

  keep-n-tagged:
    description: >
      Number of tagged images to keep (sorted by date)
    required: false

  exclude-tags:
    description: >
      Tags to exclude from deletion (comma seperated)
    required: false

  validate:
    description: >
      Validate all multi architecture images manifests by checking their digests
      are present in the registry

  dry-run:
    description: >
      Simulate action - does not remove any packages
    required: false

  log-level:
    description: >
      Log level (error/warn/info/debug)
    required: false

runs:
  using: node20
  main: dist/index.js
