name: Integration Tests

on: [pull_request, push]

jobs:
  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      packages: write
      contents: read
      attestations: write
    concurrency:
      group: integeration-tests
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

      - name: Build Tester
        run: npm run ci-tester

      # untagged test
      - name: Prime Test - Untagged
        run:
          node citester/index.js --token ${{ secrets.GITHUB_TOKEN }} --directory
          tests/untagged --mode prime
      - name: Run Test - Untagged
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Validate Test Results - Untagged
        run:
          node citester/index.js --token ${{ secrets.GITHUB_TOKEN }} --directory
          tests/untagged --mode validate

      # tagged test
      - name: Prime Test - Tagged
        run:
          node citester/index.js --token ${{ secrets.GITHUB_TOKEN }} --directory
          tests/tagged --mode prime
      - name: Run Test - Tagged
        uses: ./
        with:
          tags: uclibc-1.35,uclibc-1.36
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Validate Test Results - Tagged
        run:
          node citester/index.js --token ${{ secrets.GITHUB_TOKEN }} --directory
          tests/tagged --mode validate

      # keep-n-tagged test
      - name: Prime Test - Keep N Tagged
        run:
          node citester/index.js --token ${{ secrets.GITHUB_TOKEN }} --directory
          tests/keep-n-tagged --mode prime --delay 3000
      - name: Run Test - Keep N Tagged
        uses: ./
        with:
          keep-n-tagged: 2
          exclude-tags: dummy
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Validate Test Results - Keep N Tagged
        run:
          node citester/index.js --token ${{ secrets.GITHUB_TOKEN }} --directory
          tests/keep-n-tagged --mode validate

      # keep-n-untagged test
      - name: Prime Test - Keep N Untagged
        run:
          node citester/index.js --token ${{ secrets.GITHUB_TOKEN }} --directory
          tests/keep-n-untagged --mode prime --delay 3000
      - name: Run Test - Keep N Untagged
        uses: ./
        with:
          keep-n-untagged: 2
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Validate Test Results - Keep N Untagged
        run:
          node citester/index.js --token ${{ secrets.GITHUB_TOKEN }} --directory
          tests/keep-n-untagged --mode validate

      # multi untagged test
      - name: Prime Test - Multi Untagged
        run:
          node citester/index.js --token ${{ secrets.GITHUB_TOKEN }} --directory
          tests/multi-untagged --mode prime
      - name: Run Test - Multi Untagged
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Validate Test Results - Multi Untagged
        run:
          node citester/index.js --token ${{ secrets.GITHUB_TOKEN }} --directory
          tests/multi-untagged --mode validate

      # multi tagged test
      - name: Prime Test - Multi Tagged
        run:
          node citester/index.js --token ${{ secrets.GITHUB_TOKEN }} --directory
          tests/multi-tagged --mode prime
      - name: Run Test - Multi Tagged
        uses: ./
        with:
          tags: uclibc-1.35,uclibc-1.36
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Validate Test Results - Multi Tagged
        run:
          node citester/index.js --token ${{ secrets.GITHUB_TOKEN }} --directory
          tests/multi-tagged --mode validate

      # multi keep-n-tagged test
      - name: Prime Test - Multi Keep N Tagged
        run:
          node citester/index.js --token ${{ secrets.GITHUB_TOKEN }} --directory
          tests/multi-keep-n-tagged --mode prime --delay 3000
      - name: Run Test - Multi Keep N Tagged
        uses: ./
        with:
          keep-n-tagged: 2
          exclude-tags: dummy
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Validate Test Results - Multi Keep N Tagged
        run:
          node citester/index.js --token ${{ secrets.GITHUB_TOKEN }} --directory
          tests/multi-keep-n-tagged --mode validate

      # multi keep-n-untagged test
      - name: Prime Test - Multi Keep N Untagged
        run:
          node citester/index.js --token ${{ secrets.GITHUB_TOKEN }} --directory
          tests/multi-keep-n-untagged --mode prime --delay 3000
      - name: Run Test - Multi Keep N Untagged
        uses: ./
        with:
          keep-n-untagged: 1
          exclude-tags: dummy
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Validate Test Results - Multi Keep N Untagged
        run:
          node citester/index.js --token ${{ secrets.GITHUB_TOKEN }} --directory
          tests/multi-keep-n-untagged --mode validate

      # dry-run test
      - name: Prime Test - Dry Run
        run:
          node citester/index.js --token ${{ secrets.GITHUB_TOKEN }} --directory
          tests/dry-run --mode prime
      - name: Run Test - Dry Run
        uses: ./
        with:
          dry-run: true
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Validate Test Results - Dry Run
        run:
          node citester/index.js --token ${{ secrets.GITHUB_TOKEN }} --directory
          tests/dry-run --mode validate

      #
      # referrer/attestation tests
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # attestation tagged test
      - name: Prime Test - Attestation Tagged
        run:
          node citester/index.js --token ${{ secrets.GITHUB_TOKEN }} --directory
          tests/attestation-tagged --mode prime
      - name: Build and push image
        id: push1
        uses: docker/build-push-action@v5.0.0
        with:
          context: tests/attestation-tagged
          file: tests/attestation-tagged/Dockerfile.image
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:test
      - name: Attest Image
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          subject-digest: ${{ steps.push1.outputs.digest }}
          push-to-registry: true
      - name: Run Test - Attestation Tagged
        uses: ./
        with:
          tags: test
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Validate Test Results - Attestation Tagged
        run:
          node citester/index.js --token ${{ secrets.GITHUB_TOKEN }} --directory
          tests/attestation-tagged --mode validate

      # attestation untagged test
      - name: Prime Test - Attestation UnTagged
        run:
          node citester/index.js --token ${{ secrets.GITHUB_TOKEN }} --directory
          tests/attestation-untagged --mode prime
      - name: Build and push image 1
        id: push2
        uses: docker/build-push-action@v5.0.0
        with:
          context: tests/attestation-untagged
          file: tests/attestation-untagged/Dockerfile.image1
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:test
      - name: Attest Image 1
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          subject-digest: ${{ steps.push2.outputs.digest }}
          push-to-registry: true
      - name: Build and push image 2
        id: push3
        uses: docker/build-push-action@v5.0.0
        with:
          context: tests/attestation-untagged
          file: tests/attestation-untagged/Dockerfile.image2
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:test
      - name: Attest Image 2
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          subject-digest: ${{ steps.push3.outputs.digest }}
          push-to-registry: true
      - name: Save Digests - Attestation UnTagged
        run:
          node citester/index.js --token ${{ secrets.GITHUB_TOKEN }} --directory
          tests/attestation-untagged --mode save-expected --tag test
      - name: Run Test - Attestation Tagged
        uses: ./
        with:
          validate: true
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Validate Test Results - Attestation Tagged
        run:
          node citester/index.js --token ${{ secrets.GITHUB_TOKEN }} --directory
          tests/attestation-untagged --mode validate
